name: Build RNV Static for Windows and Linux

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v7

      - name: Configurar entorno MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-expat
            mingw-w64-x86_64-upx
            unzip
            curl

      - name: Descargar, compilar, limpiar y comprimir
        shell: msys2 {0}
        run: |
          curl -O http://ftp.davidashen.net/PreTI/RNV/rnv-1.7.8.zip
          unzip rnv-1.7.8.zip
          cd rnv-1.7.8

          # Compilar estáticamente omitiendo rvp
          make CC=gcc LDFLAGS="-static" rnv

          # 1. Eliminar símbolos de depuración (strip)
          strip rnv.exe

          # 2. Comprimir el binario al máximo (UPX)
          upx --best rnv.exe

          ls -la rnv.exe

          # 3. Prueba de ejecución
          ./rnv.exe -h || true

      - name: Guardar el ejecutable de Windows (Artifact)
        uses: actions/upload-artifact@v7
        with:
          name: rnv-windows-exe
          path: rnv-1.7.8/rnv.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v7

      - name: Instalar dependencias para compilar estáticamente en Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make libexpat1-dev upx-ucl curl unzip binutils

      - name: Descargar, compilar, limpiar y comprimir
        run: |
          curl -O http://ftp.davidashen.net/PreTI/RNV/rnv-1.7.8.zip
          unzip rnv-1.7.8.zip
          cd rnv-1.7.8

          # Compilar estáticamente omitiendo rvp
          make CC=gcc LDFLAGS="-static" rnv

          # 1. Eliminar símbolos de depuración (strip)
          strip rnv

          # 2. Comprimir el binario al máximo (UPX)
          upx --best rnv

          ls -la rnv

          # 3. Prueba de ejecución
          ./rnv -h || true

      - name: Guardar el ejecutable de Linux (Artifact)
        uses: actions/upload-artifact@v7
        with:
          name: rnv-linux-bin
          path: rnv-1.7.8/rnv
